// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ION.IOS.ViewController.Settings {
	public partial class SettingsLabelCell : UITableViewCell {
		public SettingsLabelCell (IntPtr handle) : base (handle) {
		}
	}
}
