// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ION.IOS.ViewController.Settings {
	public partial class SettingsViewController : UIViewController {
		public SettingsViewController (IntPtr handle) : base (handle) {
		}
	}
}
