// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ION.IOS.ViewController.Main {
	public partial class AnalyzerViewController : UIViewController {
		public AnalyzerViewController (IntPtr handle) : base (handle) {
		}
	}
}
