// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using ION.Core.Util;

namespace ION.IOS.ViewController.Main {
	public partial class HeaderCell : UITableViewCell, IReleasable {
    /// <summary>
    /// The action that will called when the options button is clicked.
    /// </summary>
    public Action onOptionsClicked;

		public HeaderCell (IntPtr handle) : base (handle) {
      // Nope
		}

    // Overridden from UITableViewCell
    public override void AwakeFromNib() {
      base.AwakeFromNib();

//      buttonOptions.BackgroundColor = UIColor.Blue;
//      buttonOptions.SetImage(UIImage.FromBundle("ic_menu_overflow"), UIControlState.Normal);
      buttonOptions.SetImage(null, UIControlState.Normal);
      buttonOptions.TintColor = UIColor.Red;
      buttonOptions.TouchUpInside += (object sender, EventArgs e) => {
        if (onOptionsClicked != null) {
          onOptionsClicked();
        }
      };
    }

    // Overridden from IReleasable
    public void Release() {
    }
	}
}
