// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using ION.Core.Util;

namespace ION.IOS.ViewController.Main {
	public partial class HeaderCell : UITableViewCell {
    /// <summary>
    /// The action that will called when the options button is clicked.
    /// </summary>
    public Action onOptionsClicked;

		public HeaderCell (IntPtr handle) : base (handle) {
      // Nope
		}

    // Overridden from UITableViewCell
    public override void AwakeFromNib() {
      base.AwakeFromNib();

      buttonOptions.TouchUpInside += (object sender, EventArgs e) => {
        if (onOptionsClicked != null) {
          onOptionsClicked();
        }
      };
    }
	}
}
