// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ION.IOS.ViewController.Main {
	public partial class SerialNumberCell : UITableViewCell {
		public SerialNumberCell (IntPtr handle) : base (handle) {
      // Nope
		}
	}
}
