// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Threading.Tasks;
using ION.Core.Sensors;
using ION.Core.Sensors.Properties;
using CoreGraphics;
using Foundation;
using UIKit;
using AllianceCustomPicker;
using ION.IOS.ViewController.DeviceManager;
using ION.IOS.ViewController.SuperheatSubcool;
using ION.IOS.ViewController.PressureTemperatureChart;
using ION.Core.Content;
using ION.Core.Devices;
using ION.Core.Util;
using ION.IOS.Util;
using ION.IOS.ViewController.Alarms;

namespace ION.IOS.ViewController.Analyzer {
  
	public partial class AnalyzerViewController : BaseIONViewController {
    public static manualEntry start = new manualEntry ();
    public static actionPopup sensorActions = new actionPopup();
    public static sensorGroup analyzerSensors = new sensorGroup ();
    public static LowHighArea lowHighSensors;
    public static AlliancePicker manualPicker;
    public static ManualView mentryView;
    public static ActionView sactionView;
    static bool UserInterfaceIdiomIsPhone {
      get { return UIDevice.CurrentDevice.UserInterfaceIdiom == UIUserInterfaceIdiom.Phone; }
    }
		public AnalyzerViewController (IntPtr handle) : base (handle) {
      
		}

    // Overridden from UIViewController
    public override void ViewDidLoad() {
      base.ViewDidLoad();
      View.BackgroundColor = UIColor.FromPatternImage (UIImage.FromBundle ("CarbonBackground"));
      lowHighSensors = new LowHighArea (View);
      mentryView = new ManualView(View);
      sactionView = new ActionView(View);

      InitNavigationBar("ic_nav_analyzer", false);

      backAction = () => {
        root.navigation.ToggleMenu();
      };

      ////CREATE SUBVIEWS
      createSensors ();

      createPickers ();

      mentryView.mmeasurementType.TouchUpInside += showManualPicker;
      mentryView.dtypeButton.TouchUpInside += showDeviceTypePicker;

      sactionView.pcloseButton.TouchUpInside += delegate {
        sactionView.pactionButton.TouchUpInside -= handleActionPopup;
      };

      mentryView.mtextValue.ShouldReturn += (textField) => {
        textField.ResignFirstResponder();
        return true;
      };

      mentryView.mcloseButton.TouchUpInside += delegate {
        mentryView.mtextValue.Text = "";
        mentryView.mView.Hidden = true;
        mentryView.mtextValue.ResignFirstResponder();
        this.View.SendSubviewToBack (mentryView.mView);
      };

      lowHighSensors.lowArea.changeFluid.TouchUpInside += delegate {
        loadSCSH(lowHighSensors.lowArea);
      };
/*
      lowHighSensors.lowArea.changePTFluid.TouchUpInside += delegate {
        loadPT(lowHighSensors.lowArea);
      };

      lowHighSensors.highArea.changeFluid.TouchUpInside += delegate {
        loadSCSH(lowHighSensors.highArea);
      }; 

      lowHighSensors.highArea.changePTFluid.TouchUpInside += delegate {
        loadPT(lowHighSensors.highArea);
      };
*/
    }
    /// <summary>
    /// CREATE ALL SENSOR SUBVIEW STARTING POSITIONS AND CENTER POINTS
    /// </summary>
    void createSensors ()
    {
      AnalyserUtilities.CreateSnapArea(analyzerSensors, View);
      AnalyserUtilities.ApplySnapArea (analyzerSensors, View);
      AnalyserUtilities.CreateLowHighArea (lowHighSensors, View);
      AnalyserUtilities.AddHighLowArea (lowHighSensors, View);
      AnalyserUtilities.CreateSensorViews(mentryView, sactionView, View);

      AddSensorGestures (analyzerSensors, analyzerSensors.snapArea1, analyzerSensors.animator, analyzerSensors.snap);
      AddSensorGestures (analyzerSensors, analyzerSensors.snapArea2, analyzerSensors.animator, analyzerSensors.snap);
      AddSensorGestures (analyzerSensors, analyzerSensors.snapArea3, analyzerSensors.animator, analyzerSensors.snap);
      AddSensorGestures (analyzerSensors, analyzerSensors.snapArea4, analyzerSensors.animator, analyzerSensors.snap);
      AddSensorGestures (analyzerSensors, analyzerSensors.snapArea5, analyzerSensors.animator, analyzerSensors.snap);
      AddSensorGestures (analyzerSensors, analyzerSensors.snapArea6, analyzerSensors.animator, analyzerSensors.snap);
      AddSensorGestures (analyzerSensors, analyzerSensors.snapArea7, analyzerSensors.animator, analyzerSensors.snap);
      AddSensorGestures (analyzerSensors, analyzerSensors.snapArea8, analyzerSensors.animator, analyzerSensors.snap);

      AddLowHighGestures ();

      sactionView.aView.Layer.CornerRadius = 10;
      mentryView.mView.Layer.CornerRadius = 10;
    }

    /// <summary>
    /// CREATE AND SHOW POPUP FOR SINGLE SENSORS
    /// </summary>
    /// <param name="popupType">Popup type.</param>
    void ShowPopup(sensor pressedArea, int popupType){
      if (pressedArea.availableView.Hidden) {
        ///IF SENSOR IS ACTIVE SET THAT SENSOR'S INFO IN THE POPUP
        sactionView.currentSensor = pressedArea.currentSensor;
        sactionView.pdeviceName.Text = pressedArea.topLabel.Text;
        sactionView.pgaugeValue.Text = pressedArea.middleLabel.Text;
        sactionView.pvalueType.Text = pressedArea.bottomLabel.Text;
        sactionView.aView.AccessibilityIdentifier = pressedArea.snapArea.AccessibilityIdentifier;
        if (pressedArea.currentSensor != null && pressedArea.currentSensor.device.isConnected) {
         
          sactionView.pconnection.Image = UIImage.FromBundle("ic_bluetooth_connected");
          sactionView.pconnectionStatus.Text = "";
          sactionView.connectionColor.BackgroundColor = UIColor.Green;
          sactionView.connectionColor.Hidden = false;

          if (pressedArea.currentSensor.device.battery > 75) {
            sactionView.pbatteryImage.Image = UIImage.FromBundle("img_battery_100");
          } else if (pressedArea.currentSensor.device.battery > 50) {
            sactionView.pbatteryImage.Image = UIImage.FromBundle("img_battery_75");
          } else if (pressedArea.currentSensor.device.battery > 25) {
            sactionView.pbatteryImage.Image = UIImage.FromBundle("img_battery_50");
          } else if (pressedArea.currentSensor.device.battery > 0) {
            sactionView.pbatteryImage.Image = UIImage.FromBundle("img_battery_25");
          } else {
            sactionView.pbatteryImage.Image = UIImage.FromBundle("img_battery_0");
          }
          sactionView.pdeviceImage.Image = pressedArea.deviceImage.Image;

        } else if (pressedArea.currentSensor != null && !pressedArea.isManual) {
          sactionView.pconnection.Image = UIImage.FromBundle("ic_bluetooth_disconnected");
          sactionView.pconnectionStatus.Text = "Disconnected";
          sactionView.pconnectionStatus.TextColor = UIColor.Red;
          sactionView.pdeviceImage.Image = pressedArea.deviceImage.Image;
          sactionView.connectionColor.BackgroundColor = UIColor.Red;
          sactionView.connectionColor.Hidden = false;
        } else {
          sactionView.pdeviceImage.Image = UIImage.FromBundle("ic_edit");
          sactionView.pconnectionStatus.Text = "";
          sactionView.pconnection.Image = null;
          sactionView.pbatteryImage.Image = null;
          sactionView.connectionColor.Hidden = true;
        }


        if (lowHighSensors.lowArea.snapArea.AccessibilityIdentifier == pressedArea.snapArea.AccessibilityIdentifier) {
          sactionView.pLowHigh.Text = "Low Side";
          sactionView.pLowHigh.BackgroundColor = UIColor.Blue;
          sactionView.pLowHigh.Layer.CornerRadius = 6f;
          sactionView.pLowHigh.TextColor = UIColor.White;
        } else if (lowHighSensors.highArea.snapArea.AccessibilityIdentifier == pressedArea.snapArea.AccessibilityIdentifier) {
          sactionView.pLowHigh.Text = "High Side";
          sactionView.pLowHigh.BackgroundColor = UIColor.Red;
          sactionView.pLowHigh.Layer.CornerRadius = 6f;
          sactionView.pLowHigh.TextColor = UIColor.White;
        } else {
          sactionView.pLowHigh.Text = "Unspecified";
          sactionView.pLowHigh.BackgroundColor = UIColor.White;
          sactionView.pLowHigh.TextColor = UIColor.Black;
        }
        ///SHOW POPUP
        sactionView.aView.Hidden = false;
        View.BringSubviewToFront (sactionView.aView);

        sactionView.pcloseButton.TouchUpInside += delegate {
          sactionView.aView.Hidden = true;
        };

        ///STORE PASSED SENSOR SUBVIEW INFORMATION FOR CHANGES
        sensorActions.pressedSensor = pressedArea;
        sensorActions.pressedView = pressedArea.snapArea;
        sensorActions.addLong = pressedArea.holdGesture;
        sensorActions.addPan = pressedArea.panGesture;
        sensorActions.topLabel = pressedArea.topLabel;
        sensorActions.middleLabel = pressedArea.middleLabel;
        sensorActions.bottomLabel = pressedArea.bottomLabel;
        sensorActions.pressedSensor.isManual = pressedArea.isManual;

        ///SHOW ACTIONSHEET FOR SENSOR OPTIONS
        sactionView.pactionButton.TouchUpInside += handleActionPopup;     

      } 
      else {

        ///SHOW ACTIONSHEET FOR ADDING A NEW SENSOR
        UIAlertController addDeviceSheet;

        addDeviceSheet = UIAlertController.Create ("Add From...", "", UIAlertControllerStyle.Alert);

        addDeviceSheet.AddAction (UIAlertAction.Create ("Device Manager", UIAlertActionStyle.Default, (action) => {
          OnRequestViewer(pressedArea);
        }));

        addDeviceSheet.AddAction (UIAlertAction.Create ("Create Manual Entry", UIAlertActionStyle.Default, (action) => {
          start = new manualEntry();
          start.addPan = pressedArea.panGesture;
          start.pressedView = pressedArea.snapArea;
          start.availableView = pressedArea.availableView;
          start.addLong = pressedArea.holdGesture;
          start.addPan = pressedArea.panGesture;
          start.topLabel = pressedArea.topLabel;
          start.middleLabel = pressedArea.middleLabel;
          start.bottomLabel = pressedArea.bottomLabel;
          start.addIcon = pressedArea.addIcon;
          start.isManual = pressedArea.isManual;

          mentryView.mdoneButton.TouchUpInside += handleManualPopup;
          View.BringSubviewToFront(mentryView.mView);
          mentryView.mView.Hidden = false;
        }));

        addDeviceSheet.AddAction (UIAlertAction.Create ("Cancel", UIAlertActionStyle.Cancel, (action) => Console.WriteLine ("Cancel Action")));
        this.View.Window.RootViewController.PresentViewController (addDeviceSheet, true, null);
      }
    }

    /// <summary>
    /// EVENT FUNCTION FOR MANUAL ENTRY POPUP
    /// </summary>
    /// <param name="sender">Sender.</param>
    /// <param name="e">E.</param>
    void handleManualPopup(object sender, EventArgs e){
      start.pressedView.AddGestureRecognizer (start.addPan);
      start.availableView.Hidden = true;
      start.pressedView.BackgroundColor = UIColor.White;
      start.topLabel.Hidden = false;
      start.middleLabel.Hidden = false;
      start.bottomLabel.Hidden = false;
      start.topLabel.Text = mentryView.dtypeButton.AccessibilityIdentifier;
      start.middleLabel.Text = mentryView.mtextValue.Text + ".00";
      start.bottomLabel.Text = mentryView.mbuttonText.Text;
      start.isManual = true;
      start.addIcon.Hidden = true;

      mentryView.mdoneButton.TouchUpInside -= handleManualPopup;
      mentryView.mtextValue.Text = "";
      mentryView.mbuttonText.Text = "psig";
      start = null;
      mentryView.mView.Hidden = true;
      mentryView.mtextValue.ResignFirstResponder();
    }

    /// <summary>
    /// EVENT FUNCTION FOR ACTION POPUP
    /// </summary>
    /// <param name="sender">Sender.</param>
    /// <param name="e">E.</param>
    void handleActionPopup(object sender, EventArgs e)
    {

      UIAlertController addDeviceSheet;

      addDeviceSheet = UIAlertController.Create("Device Actions", "", UIAlertControllerStyle.ActionSheet);

      UIPopoverPresentationController presentationPopover = addDeviceSheet.PopoverPresentationController;
      if (presentationPopover!=null) {
        presentationPopover.SourceView = this.View;
        presentationPopover.PermittedArrowDirections = UIPopoverArrowDirection.Right;
      }

      addDeviceSheet.AddAction (UIAlertAction.Create ("Alarms", UIAlertActionStyle.Default, (action) => {
        alarmRequestViewer(sensorActions);
      }));
      addDeviceSheet.AddAction (UIAlertAction.Create ("Rename", UIAlertActionStyle.Default, (action) => {
        renamePopup();
      }));
      addDeviceSheet.AddAction (UIAlertAction.Create ("Remove Sensor", UIAlertActionStyle.Default, (action) => {
        AnalyserUtilities.RemoveDevice(sensorActions, lowHighSensors);
        sactionView.pactionButton.TouchUpInside -= handleActionPopup;
        sactionView.aView.Hidden = true;
      }));

      addDeviceSheet.AddAction (UIAlertAction.Create ("Cancel", UIAlertActionStyle.Cancel, (action) => Console.WriteLine ("Cancel Action")));
      this.View.Window.RootViewController.PresentViewController (addDeviceSheet, true, null);
    }
      /// <summary>
      /// SHOWS THE PICKER FOR THE MEASUREMENT TYPES
      /// </summary>
      /// <param name="sender">Sender.</param>
      /// <param name="e">E.</param>
    void showManualPicker(object sender, EventArgs e){
      manualPicker.Show ();
      mentryView.mtextValue.ResignFirstResponder();
    }
    /// <summary>
    /// SHOWS THE ALERT FOR WHAT TYPE OF DEVICE TO USE
    /// </summary>
    /// <param name="sender">Sender.</param>
    /// <param name="e">E.</param>
    void showDeviceTypePicker(object sender, EventArgs e){
      mentryView.dtypeButton.AccessibilityIdentifier = "Pressure";
      UIAlertController dtypeAlert = UIAlertController.Create ("Choose Device Type", "", UIAlertControllerStyle.Alert);

      dtypeAlert.AddAction (UIAlertAction.Create ("Pressure", UIAlertActionStyle.Default, (action) => {
        mentryView.dtypeButton.SetTitle("Pressure", UIControlState.Normal);
        mentryView.dtypeButton.AccessibilityIdentifier = "Pressure";
        manualPicker.PlainPickerItems = start.pressures;
        mentryView.mbuttonText.Text = start.pressures[0];
      }));
      dtypeAlert.AddAction (UIAlertAction.Create ("Temperature", UIAlertActionStyle.Default, (action) => {
        mentryView.dtypeButton.SetTitle("Temperature", UIControlState.Normal);
        mentryView.dtypeButton.AccessibilityIdentifier = "Temperature";
        manualPicker.PlainPickerItems = start.temperatures;
        mentryView.mbuttonText.Text = start.temperatures[0];
      }));
      dtypeAlert.AddAction (UIAlertAction.Create ("Vacuum", UIAlertActionStyle.Default, (action) => {
        mentryView.dtypeButton.SetTitle("Vacuum", UIControlState.Normal);
        mentryView.dtypeButton.AccessibilityIdentifier = "Vacuum";
        manualPicker.PlainPickerItems = start.vacuum;
        mentryView.mbuttonText.Text = start.vacuum[0];
      }));
      dtypeAlert.AddAction (UIAlertAction.Create ("Cancel", UIAlertActionStyle.Cancel, (action) => {}));
      this.View.Window.RootViewController.PresentViewController (dtypeAlert, true, null);
    }
    /// <summary>
    /// POPUP TO DETERMINE LOW/HIGH AREA ACTIONS
    /// </summary>
    /// <param name="pressedArea">LOCATION OF SENSOR</param>
    public void ShowPopup(UITableView tableArea, UIView pressedArea, lowHighSensor lowHighArea, sensor removeSensor, string middleText){    
      UIAlertController addDeviceSheet;
      ///LOW/HIGH AREA IS ASSOCIATED WITH A SINGLE SENSOR ALREADY
      if (pressedArea.AccessibilityIdentifier != "low" && pressedArea.AccessibilityIdentifier != "high") {
        addDeviceSheet = UIAlertController.Create (lowHighArea.LabelTop.Text + " Actions", "", UIAlertControllerStyle.Alert);

        addDeviceSheet.AddAction (UIAlertAction.Create ("Add Subview", UIAlertActionStyle.Default, (action) => {
          subviewOptionChosen(lowHighArea);
        }));

//        addDeviceSheet.AddAction (UIAlertAction.Create ("Alarms", UIAlertActionStyle.Default, (action) => {
//         
//        }));

        addDeviceSheet.AddAction (UIAlertAction.Create ("Remove Sensor", UIAlertActionStyle.Default, (action) => {
          AnalyserUtilities.RemoveDevice (lowHighArea, removeSensor, middleText);
        }));

      } else {
        addDeviceSheet = UIAlertController.Create ("Add From...", "", UIAlertControllerStyle.Alert);

        addDeviceSheet.AddAction (UIAlertAction.Create ("Device Manager", UIAlertActionStyle.Default, (action) => {
          if(!AnalyserUtilities.freeSpot(analyzerSensors,lowHighArea.snapArea.AccessibilityIdentifier)){
            showFullAlert();
          } else {
            lhOnRequestViewer(lowHighArea);
          }
        }));

        addDeviceSheet.AddAction (UIAlertAction.Create ("Create Manual Entry", UIAlertActionStyle.Default, (action) => {

          if(!AnalyserUtilities.freeSpot(analyzerSensors,lowHighArea.snapArea.AccessibilityIdentifier)){
            showFullAlert();
          } else {
            start = new manualEntry();
            start.pressedView = pressedArea;
            start.topLabel = lowHighArea.LabelTop;
            start.middleLabel = lowHighArea.LabelMiddle;
            start.bottomLabel = lowHighArea.LabelBottom;
            start.subviewLabel = lowHighArea.LabelSubview;
            mentryView.mView.AccessibilityIdentifier = "Pressure";

            mentryView.mdoneButton.TouchUpInside += handleManualLHPopup;
            View.BringSubviewToFront(mentryView.mView);
            mentryView.mView.Hidden = false;
          }
        }));
      }

      addDeviceSheet.AddAction (UIAlertAction.Create ("Cancel", UIAlertActionStyle.Cancel, (action) => {}));

      this.View.Window.RootViewController.PresentViewController (addDeviceSheet, true, null);
    }
    /// <summary>
    /// EVENT FUNCTION FOR LOW HIGH MANUAL POPUP. ASSOCIATES A SINGLE SENSOR TO THE LOW/HIGH AREA WHEN MAKING A MANUAL LOW/HIGH ENTRY
    /// </summary>
    /// <param name="sender">Sender.</param>
    /// <param name="e">E.</param>
    void handleManualLHPopup(object sender, EventArgs e){

      if (start.pressedView.AccessibilityIdentifier == "low") {
        for (int i = 0; i < 4; i++) {
          if (!analyzerSensors.viewList[i].availableView.Hidden) {
            start.pressedView.AccessibilityIdentifier = analyzerSensors.viewList [i].snapArea.AccessibilityIdentifier;
            start.topLabel.Hidden = false;
            start.middleLabel.Hidden = false;
            start.bottomLabel.Hidden = false;
            start.topLabel.Text = mentryView.dtypeButton.AccessibilityIdentifier + ": " + mentryView.dtypeButton.AccessibilityIdentifier [0] + mentryView.dtypeButton.AccessibilityIdentifier [1] + mentryView.dtypeButton.AccessibilityIdentifier [2] + mentryView.dtypeButton.AccessibilityIdentifier [3];
            start.middleLabel.Font = UIFont.FromName("Helvetica-Bold", 42f);
            start.middleLabel.Text = mentryView.mtextValue.Text + ".00";
            start.bottomLabel.Text = mentryView.mbuttonText.Text;
            start.subviewLabel.BackgroundColor = UIColor.Blue;
            start.subviewLabel.Text = mentryView.dtypeButton.AccessibilityIdentifier + "'s Subviews";
            lowHighSensors.lowArea.headingDivider.Hidden = false;
            lowHighSensors.lowArea.DeviceImage.Image = UIImage.FromBundle("ic_edit");
            lowHighSensors.lowArea.DeviceImage.Hidden = false;
            lowHighSensors.lowArea.isManual = true;
            Console.WriteLine("transfer type: " + mentryView.mView.AccessibilityIdentifier);
            lowHighSensors.lowArea.manualGType = mentryView.mView.AccessibilityIdentifier;
            analyzerSensors.viewList [i].addIcon.Hidden = true;
            analyzerSensors.viewList [i].availableView.Hidden = true;
            analyzerSensors.viewList [i].snapArea.BackgroundColor = UIColor.White;
            analyzerSensors.viewList [i].snapArea.AddGestureRecognizer (analyzerSensors.viewList [i].panGesture);
            analyzerSensors.viewList [i].topLabel.Text = start.topLabel.Text;
            analyzerSensors.viewList [i].tLabelBottom.BackgroundColor = UIColor.Blue;
            analyzerSensors.viewList [i].tLabelBottom.Hidden = false;
            analyzerSensors.viewList [i].middleLabel.Text = start.middleLabel.Text;
            analyzerSensors.viewList [i].bottomLabel.Text = start.bottomLabel.Text;
            analyzerSensors.viewList [i].topLabel.Hidden = false;
            analyzerSensors.viewList [i].topLabel.BackgroundColor = UIColor.Blue;
            analyzerSensors.viewList [i].topLabel.TextColor = UIColor.White;
            analyzerSensors.viewList [i].middleLabel.Hidden = false;
            analyzerSensors.viewList [i].bottomLabel.Hidden = false;
            break;
          }
        }
      } else if (start.pressedView.AccessibilityIdentifier == "high") {
        for (int i = 4; i < 8; i++) {
          if (!analyzerSensors.viewList [i].availableView.Hidden) {
            start.pressedView.AccessibilityIdentifier = analyzerSensors.viewList [i].snapArea.AccessibilityIdentifier;
            start.topLabel.Hidden = false;
            start.middleLabel.Hidden = false;
            start.bottomLabel.Hidden = false;
            start.topLabel.Text = mentryView.dtypeButton.AccessibilityIdentifier + ": " + mentryView.dtypeButton.AccessibilityIdentifier [0] + mentryView.dtypeButton.AccessibilityIdentifier [1] + mentryView.dtypeButton.AccessibilityIdentifier [2] + mentryView.dtypeButton.AccessibilityIdentifier [3];
            start.middleLabel.Font = UIFont.FromName("Helvetica-Bold", 42f);
            start.middleLabel.Text = mentryView.mtextValue.Text + ".00";
            start.bottomLabel.Text = mentryView.mbuttonText.Text;
            start.subviewLabel.BackgroundColor = UIColor.Red;
            start.subviewLabel.Text = mentryView.dtypeButton.AccessibilityIdentifier + "'s Subviews";
            lowHighSensors.highArea.headingDivider.Hidden = false;
            lowHighSensors.highArea.isManual = true;
            lowHighSensors.highArea.manualGType = mentryView.mView.AccessibilityIdentifier;
            lowHighSensors.highArea.DeviceImage.Image = UIImage.FromBundle("ic_edit");
            lowHighSensors.highArea.DeviceImage.Hidden = false;
            analyzerSensors.viewList[i].addIcon.Hidden = true;
            analyzerSensors.viewList[i].availableView.Hidden = true;
            analyzerSensors.viewList [i].snapArea.BackgroundColor = UIColor.White;
            analyzerSensors.viewList [i].snapArea.AddGestureRecognizer (analyzerSensors.viewList [i].panGesture);
            analyzerSensors.viewList [i].topLabel.Text = start.topLabel.Text;
            analyzerSensors.viewList [i].tLabelBottom.BackgroundColor = UIColor.Red;
            analyzerSensors.viewList [i].tLabelBottom.Hidden = false;
            analyzerSensors.viewList [i].middleLabel.Text = start.middleLabel.Text;
            analyzerSensors.viewList [i].bottomLabel.Text = start.bottomLabel.Text;
            analyzerSensors.viewList [i].topLabel.Hidden = false;
            analyzerSensors.viewList [i].topLabel.BackgroundColor = UIColor.Red;
            analyzerSensors.viewList [i].topLabel.TextColor = UIColor.White;
            analyzerSensors.viewList [i].middleLabel.Hidden = false;
            analyzerSensors.viewList [i].bottomLabel.Hidden = false;
            break;
          }
        }
      }

      mentryView.mdoneButton.TouchUpInside -= handleManualLHPopup;
      mentryView.dtypeButton.SetTitle ("Pressure", UIControlState.Normal);
      mentryView.mtextValue.Text = "";
      mentryView.mbuttonText.Text = start.pressures[0];
      start = null;
      mentryView.mView.Hidden = true;
      mentryView.mtextValue.ResignFirstResponder();
    }

    /// <summary>
    /// CREATE GESTURE RECOGNIZERS FOR DRAG/DROP AND LONG PRESS
    /// </summary>
    void AddSensorGestures(sensorGroup sensorGroup, sensor Sensor, UIDynamicAnimator animator, UISnapBehavior snap){
      ////CREATE OFFSETS TO FOLLOW EACH SUBVIEW AS IT MOVES

      nfloat dx = 0;
      nfloat dy = 0;

      Sensor.panGesture = new UIPanGestureRecognizer (() => {
        if (Sensor.panGesture.State == UIGestureRecognizerState.Began) {

        }
        if ((Sensor.panGesture.State == UIGestureRecognizerState.Began || Sensor.panGesture.State == UIGestureRecognizerState.Changed) && (Sensor.panGesture.NumberOfTouches == 1)) {

          // remove any previosuly applied snap behavior to avoid a flicker that will occur if both the gesture and physics are operating on the view simultaneously
          if (snap != null)
            animator.RemoveBehavior (snap);

          var p0 = Sensor.panGesture.LocationInView (View);

          if (dx == 0) {
            dx = p0.X - Sensor.snapArea.Center.X;
          }

          if (dy == 0) {
            dy = p0.Y - Sensor.snapArea.Center.Y;
          }

          // this is where the offsets are applied so that the location of the image follows the point where the image is touched as it is dragged,
          // otherwise the center of the image would snap to the touch point at the start of the pan gesture

          var p1 = new CGPoint (p0.X - dx, p0.Y - dy);

          Sensor.snapArea.Center = p1;


        } else if (Sensor.panGesture.State == UIGestureRecognizerState.Ended) {

          // reset offsets when dragging ends so that they will be recalculated for next touch and drag that occurs
          dx = 0;
          dy = 0;

          /// CHECK IF SENSOR WAS DROPPED IN LOW OR HIGH SECTION

          AnalyserUtilities.updateLowHighArea(Sensor.panGesture.LocationInView(View), Sensor, lowHighSensors, sensorGroup, View);

          ////FIGURE OUT WHERE TO SNAP THE SUBVIEW BASED ON IT'S LOCATION AND IDENTIFIER
          AnalyserUtilities.sensorSwap (sensorGroup, Convert.ToInt32(Sensor.snapArea.AccessibilityIdentifier), Sensor.panGesture.LocationInView (View), View);
        } else if (Sensor.panGesture.State == UIGestureRecognizerState.Failed) {
          Console.WriteLine ("Touch has failed to be recognized for "+Sensor.snapArea.AccessibilityIdentifier+" area");
        }
      });

      Sensor.holdGesture = new UILongPressGestureRecognizer (() => {
        if (Sensor.holdGesture.State == UIGestureRecognizerState.Began) {

        }
      });

      Sensor.shortPressGesture = new UITapGestureRecognizer (() => {
        if(Sensor.shortPressGesture.State == UIGestureRecognizerState.Ended){
          ShowPopup(Sensor, 1);
        }
      });     

      Sensor.snapArea.AddGestureRecognizer (Sensor.shortPressGesture);
    }
    /// <summary>
    /// Adds the low high gestures.
    /// </summary>
    /// <param name="analyzerSensors">Analyzer sensors.</param>
    void AddLowHighGestures(){

      lowHighSensors.lowArea.shortPress = new UITapGestureRecognizer (() => {
        if(lowHighSensors.lowArea.snapArea.AccessibilityIdentifier == "1"){ShowPopup(lowHighSensors.lowArea.subviewTable, lowHighSensors.lowArea.snapArea, lowHighSensors.lowArea,analyzerSensors.snapArea1,"Low Viewer Not Defined");}
        else if (lowHighSensors.lowArea.snapArea.AccessibilityIdentifier == "2"){ShowPopup(lowHighSensors.lowArea.subviewTable, lowHighSensors.lowArea.snapArea, lowHighSensors.lowArea,analyzerSensors.snapArea2,"Low Viewer Not Defined");}
        else if (lowHighSensors.lowArea.snapArea.AccessibilityIdentifier == "3"){ShowPopup(lowHighSensors.lowArea.subviewTable, lowHighSensors.lowArea.snapArea, lowHighSensors.lowArea,analyzerSensors.snapArea3,"Low Viewer Not Defined");}
        else if (lowHighSensors.lowArea.snapArea.AccessibilityIdentifier == "4"){ShowPopup(lowHighSensors.lowArea.subviewTable, lowHighSensors.lowArea.snapArea, lowHighSensors.lowArea,analyzerSensors.snapArea4,"Low Viewer Not Defined");}
        else if (lowHighSensors.lowArea.snapArea.AccessibilityIdentifier == "5"){ShowPopup(lowHighSensors.lowArea.subviewTable, lowHighSensors.lowArea.snapArea, lowHighSensors.lowArea,analyzerSensors.snapArea5,"Low Viewer Not Defined");}
        else if (lowHighSensors.lowArea.snapArea.AccessibilityIdentifier == "6"){ShowPopup(lowHighSensors.lowArea.subviewTable, lowHighSensors.lowArea.snapArea, lowHighSensors.lowArea,analyzerSensors.snapArea6,"Low Viewer Not Defined");}
        else if (lowHighSensors.lowArea.snapArea.AccessibilityIdentifier == "7"){ShowPopup(lowHighSensors.lowArea.subviewTable, lowHighSensors.lowArea.snapArea, lowHighSensors.lowArea,analyzerSensors.snapArea7,"Low Viewer Not Defined");}
        else if (lowHighSensors.lowArea.snapArea.AccessibilityIdentifier == "8"){ShowPopup(lowHighSensors.lowArea.subviewTable, lowHighSensors.lowArea.snapArea, lowHighSensors.lowArea,analyzerSensors.snapArea8,"Low Viewer Not Defined");}
        else {ShowPopup(lowHighSensors.lowArea.subviewTable, lowHighSensors.lowArea.snapArea, lowHighSensors.lowArea, analyzerSensors.snapArea1,"Low Viewer Not Defined");}
      });

      lowHighSensors.highArea.shortPress = new UITapGestureRecognizer (() => {
        if(lowHighSensors.highArea.snapArea.AccessibilityIdentifier == "1"){ShowPopup(lowHighSensors.highArea.subviewTable, lowHighSensors.highArea.snapArea, lowHighSensors.highArea, analyzerSensors.snapArea1,"High Viewer Not Defined");}
        else if (lowHighSensors.highArea.snapArea.AccessibilityIdentifier == "2"){ShowPopup(lowHighSensors.highArea.subviewTable, lowHighSensors.highArea.snapArea, lowHighSensors.highArea, analyzerSensors.snapArea2,"High Viewer Not Defined");}
        else if (lowHighSensors.highArea.snapArea.AccessibilityIdentifier == "3"){ShowPopup(lowHighSensors.highArea.subviewTable, lowHighSensors.highArea.snapArea, lowHighSensors.highArea, analyzerSensors.snapArea3,"High Viewer Not Defined");}
        else if (lowHighSensors.highArea.snapArea.AccessibilityIdentifier == "4"){ShowPopup(lowHighSensors.highArea.subviewTable, lowHighSensors.highArea.snapArea, lowHighSensors.highArea, analyzerSensors.snapArea4,"High Viewer Not Defined");}
        else if (lowHighSensors.highArea.snapArea.AccessibilityIdentifier == "5"){ShowPopup(lowHighSensors.highArea.subviewTable, lowHighSensors.highArea.snapArea, lowHighSensors.highArea, analyzerSensors.snapArea5,"High Viewer Not Defined");}
        else if (lowHighSensors.highArea.snapArea.AccessibilityIdentifier == "6"){ShowPopup(lowHighSensors.highArea.subviewTable, lowHighSensors.highArea.snapArea, lowHighSensors.highArea, analyzerSensors.snapArea6,"High Viewer Not Defined");}
        else if (lowHighSensors.highArea.snapArea.AccessibilityIdentifier == "7"){ShowPopup(lowHighSensors.highArea.subviewTable, lowHighSensors.highArea.snapArea, lowHighSensors.highArea, analyzerSensors.snapArea7,"High Viewer Not Defined");}
        else if (lowHighSensors.highArea.snapArea.AccessibilityIdentifier == "8"){ShowPopup(lowHighSensors.highArea.subviewTable, lowHighSensors.highArea.snapArea, lowHighSensors.highArea, analyzerSensors.snapArea8,"High Viewer Not Defined");}
        else {ShowPopup(lowHighSensors.highArea.subviewTable, lowHighSensors.highArea.snapArea, lowHighSensors.highArea, analyzerSensors.snapArea1,"High Viewer Not Defined");}
      });

      lowHighSensors.lowArea.snapArea.AddGestureRecognizer (lowHighSensors.lowArea.shortPress);
      lowHighSensors.highArea.snapArea.AddGestureRecognizer (lowHighSensors.highArea.shortPress);
    }  
    /// <summary>
    /// Popup to show available subview options to add to LOW / HIGH area
    /// </summary>
    /// <param name="pressedArea">The LOW or High section pressed</param>
    void subviewOptionChosen(lowHighSensor pressedArea){
      UIAlertController subviewAlert = UIAlertController.Create ("Choose a subview", "", UIAlertControllerStyle.Alert);
      foreach (string subview in lowHighSensors.availableSubviews) {
        var splits = subview.Split(' ');

        if (!pressedArea.tableSubviews.Contains (splits[0])) {          
          subviewAlert.AddAction (UIAlertAction.Create (subview, UIAlertActionStyle.Default, (action) => {
          pressedArea.tableSubviews.Add(splits[0]);
          pressedArea.subviewTable.Source = new AnalyzerTableSource(pressedArea.tableSubviews, splits[0], pressedArea);
          pressedArea.subviewTable.ReloadData();
          if(pressedArea.subviewTable.Hidden)
            pressedArea.subviewTable.Hidden = false;
          }));
        }
      }

      subviewAlert.AddAction (UIAlertAction.Create ("Cancel", UIAlertActionStyle.Cancel, (action) => {}));
      PresentViewController (subviewAlert, true, null);
    }
    /// <summary>
    /// creates the unit picker object for choosing the measurement type
    /// </summary>
    void createPickers (){
      manualPicker = new AlliancePicker (this);
      manualPicker.PlainPickerItems = start.pressures;
      manualPicker.SourceField = mentryView.mbuttonText;
      manualPicker.Type = PickerType.List;
      manualPicker.HeaderTitle = "Unit Picker";
    }
    /// <summary>
    /// Shows the popup to rename a sensor
    /// </summary>
    void renamePopup(){
      UIAlertController textAlert = UIAlertController.Create ("Enter Name", sensorActions.topLabel.Text, UIAlertControllerStyle.Alert);
      textAlert.AddTextField(textField => {});
      textAlert.AddAction (UIAlertAction.Create ("Cancel", UIAlertActionStyle.Cancel, UIAlertAction => {}));
      textAlert.AddAction (UIAlertAction.Create ("OK - Save", UIAlertActionStyle.Default, UIAlertAction => {
        sensorActions.topLabel.Text = textAlert.TextFields[0].Text;
        sactionView.pdeviceName.Text = textAlert.TextFields[0].Text;
        if (lowHighSensors.lowArea.snapArea.AccessibilityIdentifier == sensorActions.pressedView.AccessibilityIdentifier){
          lowHighSensors.lowArea.LabelTop.Text = textAlert.TextFields[0].Text;
          lowHighSensors.lowArea.LabelSubview.Text = textAlert.TextFields[0].Text +"'s Subviews";
        } else if (lowHighSensors.highArea.snapArea.AccessibilityIdentifier == sensorActions.pressedView.AccessibilityIdentifier){
          lowHighSensors.highArea.LabelTop.Text = textAlert.TextFields[0].Text;
          lowHighSensors.highArea.LabelSubview.Text = textAlert.TextFields[0].Text +"'s Subviews";
        }
      }));
      this.View.Window.RootViewController.PresentViewController(textAlert, true, null);
    }

    /// <summary>
    /// Called to inflate the device manager viewcontroller and allow BT connections for single sensors
    /// </summary>
    private void OnRequestViewer(sensor area) {
      bool existingConnection = false;
      var sb = InflateViewController<DeviceManagerViewController>(VC_DEVICE_MANAGER);
      sb.onSensorReturnDelegate = (GaugeDeviceSensor sensor) => {
       // string returnedSerial = sensor.device.serialNumber.ToString();
        foreach(sensor item in analyzerSensors.viewList){
          if(item.currentSensor != null && item.currentSensor.device.serialNumber == sensor.device.serialNumber){
            existingConnection = true;
            break;
          }
 
        }
        if(!existingConnection){
          area.currentSensor = sensor;
          area.deviceImage.Image = UIImage.FromBundle("ic_render_gauge_" + area.currentSensor.device.serialNumber.deviceModel.ToString().ToLower());
          area.connectionImage.Image = UIImage.FromBundle("ic_bluetooth_connected");
          area.snapArea.BackgroundColor = UIColor.White;
          area.availableView.Hidden = true;
          area.snapArea.AddGestureRecognizer(area.panGesture);
          area.topLabel.Text = sensor.device.name;
          area.topLabel.Hidden = false;
          area.middleLabel.Text = sensor.measurement.amount.ToString();
          area.middleLabel.Hidden = false;
          area.bottomLabel.Text = sensor.measurement.unit.ToString();
          area.bottomLabel.Hidden = false;
          area.addIcon.Hidden = true;
        }
      };
      NavigationController.PushViewController(sb, true);
    }

    /// <summary>
    /// Called to inflate the device manager viewcontroller and allow BT connections for single sensors
    /// </summary>
    private void lhOnRequestViewer(lowHighSensor area) {
      bool existingConnection = false;
      int start, stop;
      var sb = InflateViewController<DeviceManagerViewController>(VC_DEVICE_MANAGER);
      sb.onSensorReturnDelegate = (GaugeDeviceSensor sensor) => {
        
        if(area.snapArea.AccessibilityIdentifier == "low"){
          start = 0;
          stop = 4;
        } else {
          start = 4;
          stop = 8;
        }

        for(int i = start; i < stop; i ++){
          if(analyzerSensors.viewList[i].currentSensor != null && analyzerSensors.viewList[i].currentSensor.device.serialNumber == sensor.device.serialNumber){

            area.snapArea.AccessibilityIdentifier = analyzerSensors.viewList[i].snapArea.AccessibilityIdentifier;
            area.currentSensor = sensor;
            area.manifold = new Manifold(area.currentSensor as Sensor);
            area.LabelTop.Text = analyzerSensors.viewList[i].topLabel.Text;
            area.LabelMiddle.Text = analyzerSensors.viewList[i].middleLabel.Text;
            area.LabelMiddle.Font = UIFont.FromName("Helvetica-Bold", 42f);
            area.LabelMiddle.TextAlignment = UITextAlignment.Right;
            area.LabelBottom.Text = analyzerSensors.viewList[i].bottomLabel.Text;
            area.LabelSubview.Text = analyzerSensors.viewList[i].topLabel.Text + "'s subviews";
            area.DeviceImage.Image = analyzerSensors.viewList[i].deviceImage.Image;
            area.DeviceImage.Hidden = false;
            area.Connection.Image = analyzerSensors.viewList[i].connectionImage.Image;
            area.Connection.Hidden = false;
            area.headingDivider.Hidden = false;
            area.connectionColor.Hidden = false;

            if(sensor.device.isConnected){
              area.Connection.Image = UIImage.FromBundle("ic_bluetooth_connected");
              area.connectionColor.BackgroundColor = UIColor.Green;
            } else {
              area.Connection.Image = UIImage.FromBundle("ic_bluetooth_disconnected");
              area.connectionColor.BackgroundColor = UIColor.Red;
            }

            if(start == 0){
              analyzerSensors.viewList[i].topLabel.BackgroundColor = UIColor.Blue;
              analyzerSensors.viewList[i].tLabelBottom.BackgroundColor = UIColor.Blue;
              area.LabelSubview.BackgroundColor = UIColor.Blue;
            } else {
              analyzerSensors.viewList[i].topLabel.BackgroundColor = UIColor.Red;
              analyzerSensors.viewList[i].tLabelBottom.BackgroundColor = UIColor.Red;
              area.LabelSubview.BackgroundColor = UIColor.Red;
            }
            analyzerSensors.viewList[i].topLabel.TextColor = UIColor.White;
            existingConnection = true;
            break;
          }
        }

        if(!existingConnection){
          for(int i = start; i < stop; i ++){
            if(!analyzerSensors.viewList[i].availableView.Hidden){
              analyzerSensors.viewList[i].currentSensor = sensor;
              area.currentSensor = sensor;
              area.manifold = new Manifold(sensor as Sensor);
              analyzerSensors.viewList[i].snapArea.BackgroundColor = UIColor.White;
              analyzerSensors.viewList[i].availableView.Hidden = true;
              analyzerSensors.viewList[i].addIcon.Hidden = true;
              analyzerSensors.viewList[i].topLabel.Text = sensor.device.name;
              analyzerSensors.viewList[i].topLabel.Hidden = false;
              analyzerSensors.viewList[i].tLabelBottom.Hidden = false;
              analyzerSensors.viewList[i].middleLabel.Text = sensor.measurement.amount.ToString();
              analyzerSensors.viewList[i].middleLabel.Hidden = false;
              analyzerSensors.viewList[i].bottomLabel.Text = sensor.measurement.unit.ToString();
              analyzerSensors.viewList[i].bottomLabel.Hidden = false;
              analyzerSensors.viewList[i].deviceImage.Image = UIImage.FromBundle("ic_render_gauge_"+sensor.device.serialNumber.deviceModel.ToString().ToLower());
              analyzerSensors.viewList[i].connectionImage.Image = UIImage.FromBundle("ic_bluetooth_connected");
              analyzerSensors.viewList[i].snapArea.AddGestureRecognizer(analyzerSensors.viewList[i].panGesture);
              area.snapArea.AccessibilityIdentifier = analyzerSensors.viewList[i].snapArea.AccessibilityIdentifier;
              area.LabelTop.Text = analyzerSensors.viewList[i].topLabel.Text;
              area.LabelMiddle.Font = UIFont.FromName("Helvetica-Bold", 42f);
              area.LabelMiddle.Text = sensor.measurement.amount.ToString();
              area.LabelBottom.Text = sensor.measurement.unit.ToString();
              area.LabelMiddle.TextAlignment = UITextAlignment.Right;
              area.LabelSubview.Text = analyzerSensors.viewList[i].topLabel.Text + "'s subviews";
              area.DeviceImage.Image = analyzerSensors.viewList[i].deviceImage.Image;
              area.DeviceImage.Hidden = false;           
              area.Connection.Hidden = false;
              area.headingDivider.Hidden = false;
              if(area.currentSensor != null && area.currentSensor.device.isConnected.Equals(true)){
                area.Connection.Image = UIImage.FromBundle("ic_bluetooth_connected");
                area.connectionColor.BackgroundColor = UIColor.Green;
                area.connectionColor.Hidden = false;
              } else if (area.currentSensor != null && !area.currentSensor.device.isConnected){
                area.Connection.Image = UIImage.FromBundle("ic_bluetooth_disconnected");
                area.connectionColor.BackgroundColor = UIColor.Red;
                area.connectionColor.Hidden = false;
              } else {
                area.connectionColor.Hidden = true;
              }


              if(start == 0){
                area.LabelSubview.BackgroundColor = UIColor.Blue;
                analyzerSensors.viewList[i].topLabel.BackgroundColor = UIColor.Blue;
                analyzerSensors.viewList[i].tLabelBottom.BackgroundColor = UIColor.Blue;
              } else {
                area.LabelSubview.BackgroundColor = UIColor.Red;               
                analyzerSensors.viewList[i].topLabel.BackgroundColor = UIColor.Red;
                analyzerSensors.viewList[i].tLabelBottom.BackgroundColor = UIColor.Red;
              }
              analyzerSensors.viewList[i].topLabel.TextColor = UIColor.White;
              break;
            }
          }

        }
        if(start == 0){
          start = 4;
          stop = 8;
        } else {
          start = 0;
          stop = 4;
        }

        for(int i = start; i < stop; i ++){
          if(analyzerSensors.viewList[i].currentSensor != null && analyzerSensors.viewList[i].currentSensor.device.serialNumber == sensor.device.serialNumber){
            analyzerSensors.viewList[i].topLabel.Hidden = true;
            analyzerSensors.viewList[i].tLabelBottom.Hidden = true;
            analyzerSensors.viewList[i].middleLabel.Hidden = true;
            analyzerSensors.viewList[i].bottomLabel.Hidden = true;
            analyzerSensors.viewList[i].snapArea.BackgroundColor = UIColor.Clear;
            analyzerSensors.viewList[i].addIcon.Hidden = false;
            analyzerSensors.viewList[i].availableView.Hidden = false;
            analyzerSensors.viewList[i].currentSensor.onSensorStateChangedEvent -= analyzerSensors.viewList[i].gaugeUpdating;
            analyzerSensors.viewList[i].currentSensor = null;
            if(lowHighSensors.lowArea.snapArea.AccessibilityIdentifier == analyzerSensors.viewList[i].snapArea.AccessibilityIdentifier){
              lowHighSensors.lowArea.LabelTop.BackgroundColor = UIColor.Clear;
              lowHighSensors.lowArea.LabelTop.TextColor = UIColor.Black;
              lowHighSensors.lowArea.subviewTable.Source = new AnalyzerTableSource(new List<string>(), "lowHighCell", area);
              lowHighSensors.lowArea.subviewTable.ReloadData ();
              lowHighSensors.lowArea.snapArea.AccessibilityIdentifier = "low";
              lowHighSensors.lowArea.LabelTop.Text = "";
              lowHighSensors.lowArea.LabelMiddle.Font = UIFont.FromName("Helvetica", 12f);
              lowHighSensors.lowArea.LabelMiddle.Text = "Low Viewer Not Defined";
              lowHighSensors.lowArea.LabelMiddle.TextAlignment = UITextAlignment.Center;
              lowHighSensors.lowArea.LabelBottom.Text = "";
              lowHighSensors.lowArea.LabelSubview.Text = "";
              lowHighSensors.lowArea.LabelSubview.ClipsToBounds = true;
              lowHighSensors.lowArea.LabelSubview.BackgroundColor = UIColor.Clear;
              lowHighSensors.lowArea.subviewTable.Hidden = true;
              lowHighSensors.lowArea.DeviceImage.Hidden = true;
              lowHighSensors.lowArea.Connection.Hidden = true;
              lowHighSensors.lowArea.connectionColor.Hidden = true;
              lowHighSensors.lowArea.headingDivider.Hidden = true;
              lowHighSensors.lowArea.tableSubviews = new List<string> ();
            } else if (lowHighSensors.highArea.snapArea.AccessibilityIdentifier == analyzerSensors.viewList[i].snapArea.AccessibilityIdentifier){
              lowHighSensors.highArea.LabelTop.BackgroundColor = UIColor.Clear;
              lowHighSensors.highArea.LabelTop.TextColor = UIColor.Black;
              lowHighSensors.highArea.subviewTable.Source = new AnalyzerTableSource(new List<string>(), "lowHighCell", area);
              lowHighSensors.highArea.subviewTable.ReloadData ();
              lowHighSensors.highArea.snapArea.AccessibilityIdentifier = "high";
              lowHighSensors.highArea.LabelTop.Text = "";
              lowHighSensors.highArea.LabelMiddle.Font = UIFont.FromName("Helvetica", 12f);
              lowHighSensors.highArea.LabelMiddle.Text = "High Viewer Not Defined";
              lowHighSensors.highArea.LabelMiddle.TextAlignment = UITextAlignment.Center;
              lowHighSensors.highArea.LabelBottom.Text = "";
              lowHighSensors.highArea.LabelSubview.Text = "";
              lowHighSensors.highArea.LabelSubview.ClipsToBounds = true;
              lowHighSensors.highArea.LabelSubview.BackgroundColor = UIColor.Clear;
              lowHighSensors.highArea.subviewTable.Hidden = true;
              lowHighSensors.highArea.DeviceImage.Hidden = true;
              lowHighSensors.highArea.Connection.Hidden = true;
              lowHighSensors.highArea.connectionColor.Hidden = true;
              lowHighSensors.highArea.headingDivider.Hidden = true;
              lowHighSensors.highArea.tableSubviews = new List<string> ();
            }
          }
        }

      };
      NavigationController.PushViewController(sb, true);
    }

    private void alarmRequestViewer(actionPopup area) {
      var alarm = InflateViewController<SensorAlarmViewController>(VC_SENSOR_ALARMS);
      alarm.sensor = area.pressedSensor.currentSensor;
      NavigationController.PushViewController(alarm, true);
    }

    public void loadSCSH(lowHighSensor Sensor){
      var scsh = InflateViewController<SuperheatSubcoolViewController>(VC_SUPERHEAT_SUBCOOL);
      scsh.initialManifold = Sensor.manifold;
      NavigationController.PushViewController(scsh, true);
    }

    public void loadPT(lowHighSensor Sensor){
      var ptc = InflateViewController<PTChartViewController>(VC_PT_CHART);
      ptc.initialManifold = Sensor.manifold;
      NavigationController.PushViewController(ptc, true);
    }

    void showFullAlert(){
      UIAlertController fullPopup = UIAlertController.Create ("Cannot Create Sensor", "Not enough space", UIAlertControllerStyle.Alert);

      fullPopup.AddAction (UIAlertAction.Create ("Ok", UIAlertActionStyle.Default, (action) => {}));            

      PresentViewController (fullPopup, true, null);
    }
	}
}
