// This file has been autogenerated from a class added in the UI designer.

using System;

using CoreGraphics;
using Foundation;
using UIKit;

using ION.Core.Util;

using ION.IOS.Util;

namespace ION.IOS.ViewController.Analyzer {
	public partial class AnalyzerViewController : BaseIONViewController {

    /// <summary>
    /// The analyzer view.
    /// </summary>
    private AnalyzerDisplayView __analyzerView;

		public AnalyzerViewController (IntPtr handle) : base (handle) {
		}

    // Overridden from UIViewController
    public override void ViewDidLoad() {
      base.ViewDidLoad();


//      Log.D(this, "Frame: " + viewAnalyzerContainer.Frame.ToString());
//      Log.D(this, "Bounds: " + viewAnalyzerContainer.Bounds.ToString());
      var frame = new CGRect(10, 10, 20, 20);
      var view = new UIView(frame);
      var f2 = new CGRect(20, 20, 200, 200);
      var an = new AnalyzerDisplayView(f2);
      view.BackgroundColor = new UIColor(Colors.BLUE);
      viewAnalyzerContainer.AddSubview(view);
      viewAnalyzerContainer.AddSubview(an);
//      viewAnalyzerContainer.AddSubview(__analyzerView = new AnalyzerDisplayView());
//      __analyzerView.Frame = viewAnalyzerContainer.Bounds;
//      __analyzerView.Invalidate();
    }
	}
}
