// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using ION.Core.Devices;

namespace ION.IOS.ViewController.DeviceManager {
	public partial class SerialNumberTableCell : UITableViewCell {
		public SerialNumberTableCell (IntPtr handle) : base (handle) {
		}

    /// <summary>
    /// Updates the cell to the given device.
    /// </summary>
    /// <param name="device">Device.</param>
    public void UpdateTo(IDevice device) {
      labelSerialNumber.Text = device.serialNumber.ToString();
    }
	}
}
