// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using ION.Core.Util;

namespace ION.IOS.ViewController.Ancillary {
	public partial class FluidCell : UITableViewCell {

    public Action onFavoriteClicked { get; set; }

		public FluidCell (IntPtr handle) : base (handle) {
      // Nope
		}

    // Overridden from UITableViewCell
    public override void AwakeFromNib() {
      base.AwakeFromNib();

      iconFavorite.Image = UIImage.FromBundle("ic_bookmark").ImageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate);
      iconFavorite.UserInteractionEnabled = true;
      iconFavorite.AddGestureRecognizer(new UITapGestureRecognizer(() => {
        Log.D(this, "Clicky, clicky");
        if (onFavoriteClicked != null) {
          onFavoriteClicked();
        }
      }));
        
      iconSelected.Image = UIImage.FromBundle("ic_check");
    }
	}
}
