// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ION.IOS.ViewController.Ancillary {
	public partial class FluidManagerViewController : UIViewController {
    public FluidManagerViewController (IntPtr handle) : base (handle) {
		}
	}
}
