// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using ION.Core.Util;

namespace ION.IOS.UI {
  /// <summary>
  /// A button who can only display ninepatches.
  /// </summary>
	public partial class NinePatchButtonView : UIButton {
		public NinePatchButtonView (IntPtr handle) : base (handle) {
		}

    // Overridden from UIButton
    public override void SetBackgroundImage(UIImage image, UIControlState state) {
      base.SetBackgroundImage(NinePatchImageFactory.CreateResizableNinePatchImage(image), state);
    }

    // Overridden from UIButton
    public override void SetImage(UIImage image, UIControlState state) {
      base.SetImage(NinePatchImageFactory.CreateResizableNinePatchImage(image), state);
    }
	}
}
