// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;

using CoreGraphics;
using Foundation;
using UIKit;

using Xfinium.Pdf;
using Xfinium.Pdf.Rendering;

using ION.Core.App;

using ION.IOS.ViewController;

namespace ION.IOS.Storyboard {
	public partial class PdfDisplayViewController : BaseIONViewController {
    public string fileName { get; set; }

		public PdfDisplayViewController (IntPtr handle) : base (handle) {
		}

    // Overridden from UIViewController
    public override void ViewDidLoad() {
      base.ViewDidLoad();


      var t = Task<CGImage>.Factory.StartNew(() => {
        return RenderPdfToImage();
      });
      t.ContinueWith(value => {
        imageView.Image = new UIImage(value.Result);
      }, TaskScheduler.FromCurrentSynchronizationContext());
    }

    private CGImage RenderPdfToImage() {
      var fm = AppState.context.fileManager;
      var file = fm.GetApplicationExternalDirectory().GetFile("Testo2.pdf");

      var d = new PdfFixedDocument(file.fullPath);
      CGImage image = null;
      PdfPageRenderer renderer = new PdfPageRenderer(d.Pages[0]);
      image = renderer.ConvertPageToImage(96);
      return image;
    }
	}
}
