// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ION.IOS
{
	public partial class RemoteAccessViewController : UIViewController
	{
		public RemoteAccessViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
