// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using ION.Core.Fluids;

using ION.IOS.Util;

namespace ION.IOS.ViewController.FluidManager {
	public partial class FluidTableCell : UITableViewCell {

    private EventHandler<string> onFavoriteClicked { get; set; }

    private string fluidName { get; set; }

		public FluidTableCell (IntPtr handle) : base (handle) {
		}

    public override void AwakeFromNib() {
      base.AwakeFromNib();

      imageFavorite.Image = UIImage.FromBundle("ic_bookmark").ImageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate);
      imageFavorite.UserInteractionEnabled = true;
      imageFavorite.AddGestureRecognizer(new UITapGestureRecognizer(() => {
        if (onFavoriteClicked != null) {
          onFavoriteClicked(this, fluidName);
        }
      }));

      imageSelected.Image = UIImage.FromBundle("ic_check");
    }

    public void UpdateTo(string fluidName, int fluidColor, bool selected, bool preferred, EventHandler<string> favoriteClicked = null) {
      this.fluidName = fluidName;
      viewFluidColor.BackgroundColor = CGExtensions.FromARGB8888(fluidColor);
      labelFluidName.Text = fluidName;
      onFavoriteClicked = favoriteClicked;

      imageSelected.Hidden = !selected;

      if (preferred) {
        imageFavorite.TintColor = new UIColor(Colors.GOLD);
      } else {
        imageFavorite.TintColor = new UIColor(Colors.BLACK);
      }
    }
	}
}
