// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using ION.Core.Fluids;

using ION.IOS.Util;
using ION.Core.App;

namespace ION.IOS.ViewController.FluidManager {
	public partial class FluidTableCell : UITableViewCell {

    private EventHandler<string> onFavoriteClicked { get; set; }

    private string fluidName { get; set; }
    
    IION ion;

		public FluidTableCell (IntPtr handle) : base (handle) {  
		}

    public override void AwakeFromNib() {
      base.AwakeFromNib();
			ion = AppState.context;
			
      imageFavorite.Image = UIImage.FromBundle("ic_bookmark").ImageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate);
      imageFavorite.UserInteractionEnabled = true;
      imageFavorite.AddGestureRecognizer(new UITapGestureRecognizer(() => {
        if (onFavoriteClicked != null) {
          onFavoriteClicked(this, fluidName);
        }
      }));
			imageSelected.Layer.CornerRadius = 5;
      //imageSelected.Image = UIImage.FromBundle("ic_check");
      imageSelected.BackgroundColor = UIColor.Red;
      imageSelected.Hidden = false;
    }

    public void UpdateTo(string fluidName, int fluidColor, bool selected, bool preferred, EventHandler<string> favoriteClicked = null) {
    	var safetyInfo = ion.fluidManager.GetFluidSafety(fluidName);
    	
      this.fluidName = fluidName;
      viewFluidColor.BackgroundColor = CGExtensions.FromARGB8888(fluidColor);
      labelFluidName.Text = fluidName;
      onFavoriteClicked = favoriteClicked;
      if(safetyInfo != Fluid.ESafety.Unknown){
				safetyClassification.Text = safetyInfo.ToString();
			} else {
				safetyClassification.Text = "N/A";
			}

			imageSelected.BackgroundColor = CGExtensions.FromARGB8888(safetyInfo.Color());
			
      if(selected){
				this.BackgroundColor = UIColor.FromRGB(176,176,176);
			} else {
				this.BackgroundColor = UIColor.White;
			}

      if (preferred) {
        imageFavorite.TintColor = new UIColor(Colors.GOLD);
      } else {
        imageFavorite.TintColor = new UIColor(Colors.BLACK);
      }
    }
	}
}
