#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ION.Droid.Resource", IsApplication=true)]

namespace ION.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int black = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int blue = 2130968582;
			
			// aapt resource value: 0x7f04000c
			public const int fluid_default = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int gold = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int gray = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int green = 2130968586;
			
			// aapt resource value: 0x7f040005
			public const int light_blue = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int light_gray = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int light_red = 2130968584;
			
			// aapt resource value: 0x7f040003
			public const int nav_gray = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int red = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int white = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int yellow = 2130968587;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050015
			public const int activity_horizontal_margin = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int activity_vertical_margin = 2131034134;
			
			// aapt resource value: 0x7f050032
			public const int arrow_height = 2131034162;
			
			// aapt resource value: 0x7f050031
			public const int arrow_width = 2131034161;
			
			// aapt resource value: 0x7f050018
			public const int device_manager_connect_icon_size = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int device_manager_device_icon_size = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int device_manager_sensor_icon_size = 2131034137;
			
			// aapt resource value: 0x7f05002a
			public const int icon_large = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int icon_medium = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int icon_small = 2131034156;
			
			// aapt resource value: 0x7f050029
			public const int icon_very_large = 2131034153;
			
			// aapt resource value: 0x7f05002d
			public const int icon_very_small = 2131034157;
			
			// aapt resource value: 0x7f050001
			public const int image_height = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int image_width = 2131034112;
			
			// aapt resource value: 0x7f05001a
			public const int keyline_1 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int keyline_1_minus_8 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int keyline_2_content = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int keyline_2_title = 2131034141;
			
			// aapt resource value: 0x7f050007
			public const int list_item_connection_icon = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int list_item_device_icon = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int list_item_horizontal_margin = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int list_item_icon_size = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int list_item_vertical_margin = 2131034117;
			
			// aapt resource value: 0x7f05002e
			public const int nav_icon = 2131034158;
			
			// aapt resource value: 0x7f05001f
			public const int nav_padding = 2131034143;
			
			// aapt resource value: 0x7f050028
			public const int navigation_drawer_width = 2131034152;
			
			// aapt resource value: 0x7f05001e
			public const int padding = 2131034142;
			
			// aapt resource value: 0x7f050013
			public const int pt_entry_size = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int pt_text_size = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int table_layout_padding = 2131034115;
			
			// aapt resource value: 0x7f050025
			public const int text_size_large = 2131034149;
			
			// aapt resource value: 0x7f050024
			public const int text_size_medium = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int text_size_small = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int text_size_tiny = 2131034146;
			
			// aapt resource value: 0x7f050027
			public const int text_size_title = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int text_size_xlarge = 2131034150;
			
			// aapt resource value: 0x7f050021
			public const int thick_separator = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int thin_separator = 2131034144;
			
			// aapt resource value: 0x7f050030
			public const int toast_icon_height = 2131034160;
			
			// aapt resource value: 0x7f05002f
			public const int toast_icon_width = 2131034159;
			
			// aapt resource value: 0x7f05000f
			public const int viewer_compact_margin_regression = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int viewer_compact_measurement = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int viewer_compact_sub_height = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int viewer_compact_text = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int viewer_margin_regression = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int viewer_measurement = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int viewer_sub_height = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int viewer_sub_text_icon = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int viewer_sub_text_primary = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int viewer_sub_text_secondary = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int viewer_sub_text_title = 2131034123;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Dimens = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int hidden_button_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_accept = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_edit = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_pause = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_play = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_alarm_active = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_alarm_add = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_arrow_downblack = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_arrow_downfloor = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_arrow_downwhite = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_arrow_trenddown = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_arrow_trendup = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_arrow_upblack = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_arrow_upcieling = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_arrow_upwhite = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_association = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_association_linked = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_battery_horiz_100 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_battery_horiz_25 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_battery_horiz_50 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_battery_horiz_75 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_battery_horiz_empty = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_bluetooth_c3_broadcast = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_bluetooth_c3_disconnected = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_bluetooth_c3_paired = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_bluetooth_connected = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_bluetooth_disconnected = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_bluetooth_nearby = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_bluetooth_unknown = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_bookmark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_compressor = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_devices_add = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_devices_add_to_analyzer = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_devices_add_to_workbench = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_devices_on_analyzer = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_devices_on_workbench = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_document = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_drawer = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_expansionchamber = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_folder = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_gears = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_link = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_logo_appiondefault = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_menu_moreoverflow = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_nav_analyzer = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_nav_certificate = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_nav_certificates = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_nav_devmanager = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_nav_power = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_nav_ptconversion = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_nav_screenshot = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_nav_supersub = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_nav_workbench = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_pdf = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_refresh = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_render_gauge_tss = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic_render_gaugeav760 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic_render_gaugep300 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic_render_gaugep500 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic_render_gaugep800 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_search = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_settings = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_subview_dropdown = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic_trash = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int Icon = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int icon_warning = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int img_bgd_carbon = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int img_bgd_dialog = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int img_bgd_list_white = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int img_bgd_subviewdisplay = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int img_button_blackclosex = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int img_button_down_gold = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int img_button_up_gold = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int img_button_whiteclosex = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int img_handle_left = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int img_handle_right = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int monoandroidsplash = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int np_analyzer_slot = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int np_blue_left_curve_corner = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int np_blue_right_curve_corner = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int np_blue_tab = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int np_bordered_gray_square = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int np_bordered_green_square = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int np_bordered_light_blue_square = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int np_bordered_light_gray_square = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int np_bordered_padding_square = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int np_bordered_red_square = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int np_bordered_transparent_square = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int np_bordered_white_square = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int np_bordered_yellow_square = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int np_empty_viewer_curve_left = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int np_empty_viewer_curve_right = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int np_half_rounded_square_lower_white = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int np_half_rounded_square_upper_blue = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int np_half_rounded_square_upper_red = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int np_half_rounded_square_upper_white = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int np_left_side_handle = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int np_rect_white_black_border = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int np_red_left_curve_corner = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int np_red_right_curve_corner = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int np_red_tab = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int np_right_side_handle = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int np_rounded_rect_blue = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int np_rounded_rect_gold = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int np_rounded_rect_green = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int np_rounded_rect_light_blue = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int np_rounded_rect_red = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int np_rounded_rect_white = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int np_rounded_square_middle = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int np_selection_bottom_gold = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int np_square_black_border_white_background = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int np_viewer_curve_left_background = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int np_viewer_curve_right_background = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int np_viewer_sub_bot = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int np_viewer_sub_handle = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int np_viewer_sub_mid = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int selector_button_close_x = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int selector_button_gold_black = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int selector_group_indicator_black = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int selector_group_indicator_white = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int selector_ic_arrow_down = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int selector_ic_arrow_up = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int selector_shsc = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int selector_text_blackgold = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int shape_circle_gold = 2130837629;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int add = 2131099648;
			
			// aapt resource value: 0x7f06000d
			public const int add_to_analyzer = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int add_to_workbench = 2131099664;
			
			// aapt resource value: 0x7f060001
			public const int arrow = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int close = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int connect = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int content = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int counter = 2131099653;
			
			// aapt resource value: 0x7f06000e
			public const int device_serial_number = 2131099662;
			
			// aapt resource value: 0x7f060006
			public const int icon = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int loading = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int measurement = 2131099663;
			
			// aapt resource value: 0x7f060008
			public const int name = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int scan = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int status = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int title = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int type = 2131099660;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_device_manager = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int button_scan = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_title = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int list_item_device_manager_device = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int list_item_device_manager_group = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int list_item_device_manager_sensor = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int list_item_device_manager_sensor_content = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int scan = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int available = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int connect = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int connected = 2131165187;
			
			// aapt resource value: 0x7f070011
			public const int device_av760 = 2131165201;
			
			// aapt resource value: 0x7f070009
			public const int device_manager_add_all_to_workbench = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int device_manager_batch_available_actions = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int device_manager_batch_connected_actions = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int device_manager_batch_disconnected_actions = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int device_manager_batch_long_range_actions = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int device_manager_batch_new_device_actions = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int device_manager_new_devices_found = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int device_manager_no_devices_found = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int device_p300 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int device_p500 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int device_p800 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int device_serial_number = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int device_type = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int device_unknown = 2131165207;
			
			// aapt resource value: 0x7f070004
			public const int disconnect_all = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int disconnected = 2131165189;
			
			// aapt resource value: 0x7f070018
			public const int long_range_mode = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int measurement = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int measurement_humidity = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int measurement_pressure = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int measurement_temperature = 2131165212;
			
			// aapt resource value: 0x7f07001e
			public const int measurement_unknown = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int measurement_vacuum = 2131165213;
			
			// aapt resource value: 0x7f070006
			public const int name = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int scan = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int scanning = 2131165192;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Mono_Android_Theme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
