// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using ION.IOS.UI;
using ION.IOS.ViewController.Ancillary;

namespace ION.IOS.ViewController.Calculators {
	public partial class PressureTemperatureViewController : UIViewController {
		public PressureTemperatureViewController (IntPtr handle) : base (handle) {
		}

    public override void ViewDidLoad() {
      base.ViewDidLoad();

      buttonHelp.TouchUpInside += (object obj, EventArgs e) => {
        Toast.New(this.View, "helpie help helperson clicked");
      };

      viewFluidTouchArea.AddGestureRecognizer(new UITapGestureRecognizer(() => {
        PresentViewController(((FluidManagerViewController)this.Storyboard.InstantiateViewController("fluidManagerViewController")), true, () => {
          
        });
      }));

      viewAssignPressureSensor.AddGestureRecognizer(new UITapGestureRecognizer(() => {
        Toast.New(this.View, "Picky picky the pressure dude");
      }));

      buttonPressureUnit.TouchUpInside += (object obj, EventArgs e) => {
        Toast.New(this.View, "PressureUnit clicked");
      };

      viewAssignTemperatureSensor.AddGestureRecognizer(new UITapGestureRecognizer(() => {
        Toast.New(this.View, "I'm all about you, man");
      }));

      buttonTemperatureUnit.TouchUpInside += (object obj, EventArgs e) => {
        Toast.New(this.View, "temperatureUnit clicked");
      };
    }
	}
}
