// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using ION.IOS.UI;
using ION.IOS.ViewController;
using ION.IOS.ViewController.Ancillary;

namespace ION.IOS.ViewController.Calculators {
	public partial class PressureTemperatureViewController : BaseIONViewController {
		public PressureTemperatureViewController (IntPtr handle) : base (handle) {
		}

    public override void ViewDidLoad() {
      base.ViewDidLoad();

      Title = "BAD STRING P/T Calculator";
      NavigationItem.RightBarButtonItem = new UIBarButtonItem("BS Help", UIBarButtonItemStyle.Plain, delegate {
        Toast.New(View, "helpie mchelperson was clicked");
      });

      View.AddGestureRecognizer(new UITapGestureRecognizer(() => {
        editPressure.ResignFirstResponder();
        editTemperature.ResignFirstResponder();
      }));

      viewFluidTouchArea.AddGestureRecognizer(new UITapGestureRecognizer(() => {
        var sb = Storyboard.InstantiateViewController("fluidManagerViewController");
        NavigationController.PushViewController(sb, true);
      }));

      viewAssignPressureSensor.AddGestureRecognizer(new UITapGestureRecognizer(() => {
        Toast.New(this.View, "Picky picky the pressure dude");
      }));

      buttonPressureUnit.TouchUpInside += (object obj, EventArgs e) => {
        Toast.New(this.View, "PressureUnit clicked");
      };

      viewAssignTemperatureSensor.AddGestureRecognizer(new UITapGestureRecognizer(() => {
        Toast.New(this.View, "I'm all about you, man");
      }));

      buttonTemperatureUnit.TouchUpInside += (object obj, EventArgs e) => {
        Toast.New(this.View, "temperatureUnit clicked");
      };
    }
	}
}
