// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using ION.Core.App;
using ION.Core.Devices;
using ION.Core.Fluids;
using ION.Core.Measure;
using ION.Core.Sensors;
using ION.Core.Util;

using ION.IOS.Devices;
using ION.IOS.UI;
using ION.IOS.Util;
using ION.IOS.ViewController;
using ION.IOS.ViewController.Main;
using ION.IOS.ViewController.Ancillary;

namespace ION.IOS.ViewController.Calculators {
	public partial class PressureTemperatureViewController : BaseIONViewController {

    private const int SECTION_DEW = 0;
    private const int SECTION_BUBBLE = 1;

    /// <summary>
    /// The ion context.
    /// </summary>
    /// <value>The ion.</value>
    public IION ion { get; set; }
    /// <summary>
    /// The pt chart that the view controller is interacting with.
    /// </summary>
    /// <value>The point chart.</value>
    public PTChart ptChart {
      get {
        return __ptChart;
      }
      set {
        __ptChart = value;
        var name = ptChart.fluid.name;
        labelFluidName.Text = name;
        viewFluidColor.BackgroundColor = CGExtensions.FromARGB8888(ion.fluidManager.GetFluidColor(name));
      }
    } PTChart __ptChart;

    /// <summary>
    /// The pressure sensor that will update the pressure input view.
    /// </summary>
    /// <value>The pressure sensor.</value>
    public Sensor pressureSensor {
      get { 
        return __pressureSensor;
      }
      set {
        if (__pressureSensor != null) {
          __pressureSensor.onSensorStateChangedEvent -= OnPressureSensorChanged;
        }

        if (value == null) {
          value = new Sensor(ESensorType.Pressure);
        }
        __pressureSensor = value;
        if (__pressureSensor is GaugeDeviceSensor) {
          ClearPressureInput();
          GaugeDeviceSensor sensor = (GaugeDeviceSensor)__pressureSensor;
          iconPressure.Image = DeviceUtil.GetUIImageFromDeviceModel(sensor.device.serialNumber.deviceModel);
          iconPressureLock.Image = UIImage.FromBundle("ic_lock");
        } else {
          iconPressure.Image = UIImage.FromBundle("ic_edit");
          iconPressureLock.Image = null;
        }

        editPressure.Enabled = editTemperature.Enabled = __pressureSensor.isEditable;

        pressureUnit = value.unit;
        __pressureSensor.onSensorStateChangedEvent += OnPressureSensorChanged;
      }
    } Sensor __pressureSensor;

    /// <summary>
    /// The unit that the pressure sensor will be set to, if editable.
    /// </summary>
    /// <value>The pressure unit.</value>
    public Unit pressureUnit {
      get {
        return __pressureUnit;
      }
      set {
        if (value == null) {
          value = Units.Pressure.PSIG;
        }
        if (pressureSensor.isEditable) {
          pressureSensor.unit = value;
          __pressureUnit = value;
          buttonPressureUnit.SetTitle(value.ToString(), UIControlState.Normal);
        }
      }
    } Unit __pressureUnit = Units.Pressure.PSIG;

    /// <summary>
    /// The temperature sensor that will update the temperature input view.
    /// </summary>
    /// <value>The temperature sensor.</value>
    public Sensor temperatureSensor {
      get {
        return __temperatureSensor;
      }
      set {
        if (__temperatureSensor != null) {
          __temperatureSensor.onSensorStateChangedEvent -= OnTemperatureSensorChanged;
        }

        if (value == null) {
          value = new Sensor(ESensorType.Temperature);
        }
        __temperatureSensor = value;
        if (__temperatureSensor is GaugeDeviceSensor) {
          ClearTemperatureInput();
          GaugeDeviceSensor sensor = (GaugeDeviceSensor)__temperatureSensor;
          iconTemperature.Image = DeviceUtil.GetUIImageFromDeviceModel(sensor.device.serialNumber.deviceModel);
          iconTemperature.Image = UIImage.FromBundle("ic_lock");
        } else {
          iconTemperature.Image = UIImage.FromBundle("ic_edit");
          iconTemperatureLock.Image = null;
        }

        editPressure.Enabled = editTemperature.Enabled = __temperatureSensor.isEditable;
        temperatureUnit = value.unit;
        __temperatureSensor.onSensorStateChangedEvent += OnTemperatureSensorChanged;
      }
    } Sensor __temperatureSensor;

    /// <summary>
    /// The unit that the tempreature sensor will be set to, if editable.
    /// </summary>
    /// <value>The temperature unit.</value>
    public Unit temperatureUnit {
      get { 
        return __temperatureUnit;
      }
      set {
        if (value == null) {
          value = Units.Temperature.FAHRENHEIT;
        }
        if (temperatureSensor.isEditable) {
          temperatureSensor.unit = value;
          __temperatureUnit = value;
          buttonTemperatureUnit.SetTitle(value.ToString(), UIControlState.Normal);
        }
      }
    } Unit __temperatureUnit;

    private bool isEditing { get; set; }

		public PressureTemperatureViewController (IntPtr handle) : base (handle) {
		}

    // Overridden from PressureTemperatureViewController
    public override void ViewDidLoad() {
      base.ViewDidLoad();

      buttonPressureUnit.SetBackgroundImage(UIImage.FromBundle("ButtonGold").AsNinePatch(), UIControlState.Normal);
      buttonTemperatureUnit.SetBackgroundImage(UIImage.FromBundle("ButtonGold").AsNinePatch(), UIControlState.Normal);
      switchDewBubble.ValueChanged += (object sender, EventArgs e) => {
        switch ((int)switchDewBubble.SelectedSegment) {
          case SECTION_DEW:
            ptChart = new PTChart(Fluid.State.Dew, ptChart.fluid, ptChart.elevation);
            break;
          case SECTION_BUBBLE:
            ptChart = new PTChart(Fluid.State.Bubble, ptChart.fluid, ptChart.elevation);
            break;
        }
      };

      ion = AppState.context;

      ptChart = new PTChart(Fluid.State.Dew, ion.fluidManager.lastUsedFluid);
      pressureSensor = new Sensor(ESensorType.Pressure, Units.Pressure.PSIG.OfScalar(0), true);
      temperatureSensor = new Sensor(ESensorType.Temperature, Units.Temperature.FAHRENHEIT.OfScalar(0), false);

      NavigationItem.Title = Strings.Fluid.PT_CALCULATOR;
      NavigationItem.RightBarButtonItem = new UIBarButtonItem(Strings.HELP, UIBarButtonItemStyle.Plain, delegate {
        var dialog = new UIAlertView(Strings.HELP, Strings.Fluid.STATE_HELP, null, Strings.OK);
        dialog.Show();
      });

      View.AddGestureRecognizer(new UITapGestureRecognizer(() => {
        editPressure.ResignFirstResponder();
        editTemperature.ResignFirstResponder();
      }));

      viewFluidTouchArea.AddGestureRecognizer(new UITapGestureRecognizer(() => {
        var sb = InflateViewController<FluidManagerViewController>("fluidManagerViewController");
        sb.onFluidSelectedDelegate = OnFluidSelected;
        NavigationController.PushViewController(sb, true);
      }));

      viewAssignPressureSensor.AddGestureRecognizer(new UITapGestureRecognizer(() => {
        var dm = InflateViewController<DeviceManagerViewController>("deviceManagerViewController");
        dm.displayFilter = new SensorTypeFilter(ESensorType.Pressure);
        dm.onSensorReturnDelegate = (GaugeDeviceSensor sensor) => {
          pressureSensor = sensor;
        };
        NavigationController.PushViewController(dm, true);
      }));

      viewAssignPressureSensor.AddGestureRecognizer(new UILongPressGestureRecognizer(() => {
        pressureSensor = null;
        ClearPressureInput();
      }));

      editPressure.AddTarget((object obj, EventArgs args) => {
        UpdateTemperature();
      }, UIControlEvent.EditingChanged);

      buttonPressureUnit.TouchUpInside += (object obj, EventArgs e) => {
        Toast.New(this.View, "PressureUnit clicked");
      };

      viewAssignTemperatureSensor.AddGestureRecognizer(new UITapGestureRecognizer(() => {
        var dm = InflateViewController<DeviceManagerViewController>("deviceManagerViewController");
        dm.displayFilter = new SensorTypeFilter(ESensorType.Temperature);
        dm.onSensorReturnDelegate = (GaugeDeviceSensor sensor) => {
          temperatureSensor = sensor;
        };
        NavigationController.PushViewController(dm, true);
      }));

      viewAssignTemperatureSensor.AddGestureRecognizer(new UILongPressGestureRecognizer(() => {
        temperatureSensor = null;
        ClearTemperatureInput();
      }));

      editTemperature.AddTarget((object obj, EventArgs args) => {
        UpdatePressure();
      }, UIControlEvent.EditingChanged);

      buttonTemperatureUnit.TouchUpInside += (object obj, EventArgs e) => {
        Toast.New(this.View, "temperatureUnit clicked");
      };
    }

    /// <summary>
    /// Called when a fluid is selected for the view controller.
    /// </summary>
    /// <param name="fluid">Fluid.</param>
    private void OnFluidSelected(Fluid fluid) {
      ptChart = new PTChart(ptChart.state, fluid, this.ptChart.elevation);
    }

    private void OnPressureSensorChanged(Sensor sensor) {
      editPressure.Text = sensor.ToFormattedString();
      buttonPressureUnit.SetTitle(sensor.unit.ToString(), UIControlState.Normal);
      if (!isEditing) {
        UpdateTemperature();
      }
    }

    private void OnTemperatureSensorChanged(Sensor sensor) {
      editTemperature.Text = sensor.ToFormattedString();
      buttonTemperatureUnit.SetTitle(sensor.unit.ToString(), UIControlState.Normal);
      if (!isEditing) {
        UpdatePressure();
      }
    }

    private void OnPressureEdited(object obj, EventArgs args) {
      UpdateTemperature();
    }

    private void OnTemperatureEdited(object obj, EventArgs args) {
      UpdatePressure();
    }

    private void UpdatePressure() {
      if (isEditing) {
        return;
      }
      isEditing = true;

      try {
        if (pressureSensor.isEditable) {
          var measurement = temperatureUnit.OfScalar(double.Parse(editTemperature.Text));
//          temperatureSensor.measurement = temperatureUnit.OfScalar(measurement);

          pressureSensor.measurement = ptChart.GetPressure(measurement).ConvertTo(pressureUnit);
        }
      } catch (Exception e) {
        Log.E(this, "Failed to UpdatePressure: invalid string " + editTemperature.Text, e);
        ClearPressureInput();
      }

      isEditing = false;
    }

    private void UpdateTemperature() {
      if (isEditing) {
        return;
      }
      isEditing = true;

      try {
        if (temperatureSensor.isEditable) {
          var measurement = pressureUnit.OfScalar(double.Parse(editPressure.Text));
//          pressureSensor.measurement = pressureUnit.OfScalar(measurement);

          temperatureSensor.measurement = ptChart.GetTemperature(measurement).ConvertTo(temperatureUnit);
        }
      } catch (Exception e) {
        Log.E(this, "Failed to UpdateTemperature: invalid string " + editPressure.Text, e);
        ClearTemperatureInput();
      }

      isEditing = false;
    }

    /// <summary>
    /// Clears the pressure input without updating the pressure sensor's reading.
    /// </summary>
    private void ClearPressureInput() {
      editPressure.Text = "";
    }

    /// <summary>
    /// Clears the temperature input without updating the temperature sensor's reading.
    /// </summary>
    private void ClearTemperatureInput() {
      editTemperature.Text = "";
    }
	}
}
