// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using ION.IOS.ViewController;

namespace ION.IOS.ViewController.Calculators {
	public partial class SuperheatSubcoolViewController : BaseIONViewController {
		public SuperheatSubcoolViewController (IntPtr handle) : base (handle) {
		}
	}
}
